import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import React from 'react';
import { TaskProvider, useTasks } from './TaskContext';
import { db } from './db';

// Mock Notification API
const mockNotification = vi.fn();
Object.defineProperty(window, 'Notification', {
  value: Object.assign(mockNotification, {
    permission: 'granted',
    requestPermission: vi.fn().mockResolvedValue('granted'),
  }),
  writable: true,
});

describe('TaskContext Notifications & Logic', () => {
  beforeEach(async () => {
    await db.clearAll();
    vi.useFakeTimers({ toFake: ['setInterval', 'setTimeout', 'Date'] });
    mockNotification.mockClear();
  });

  afterEach(() => {
    vi.useRealTimers();
  });

  it('should fire notification when task is due', async () => {
    const wrapper = ({ children }: { children: React.ReactNode }) => (
      <TaskProvider>{children}</TaskProvider>
    );

    const { result } = renderHook(() => useTasks(), { wrapper });

    // Wait for initial load
    await act(async () => {
      // Small advance to let promises resolve
      await vi.advanceTimersByTimeAsync(1);
    });

    const now = Date.now();
    await act(async () => {
      await result.current.addTask('Due Task', {
        remindMe: true,
        dateDue: now + 5000,
      });
    });

    // Advance time past the due date (10s interval + 5s wait)
    await act(async () => {
      await vi.advanceTimersByTimeAsync(15000);
    });

    expect(mockNotification).toHaveBeenCalledWith('QDO Task Due', expect.objectContaining({
      body: 'Task "Due Task" is due now!',
    }));
  });

  it('should merge imported tasks correctly via URL/JSON state', async () => {
    const wrapper = ({ children }: { children: React.ReactNode }) => (
      <TaskProvider>{children}</TaskProvider>
    );

    const { result } = renderHook(() => useTasks(), { wrapper });

    await act(async () => {
      await vi.advanceTimersByTimeAsync(1);
    });

    await act(async () => {
      await result.current.addTask('Local Task');
    });

    const initialTasks = result.current.tasks;
    expect(initialTasks).toHaveLength(1);

    const importedTasks: any[] = [
      {
        id: 'imported-1',
        title: 'Imported Task',
        status: 'queue',
        queueOrder: 1,
        dateAdded: Date.now(),
        dateModified: Date.now(),
        remindMe: false,
        customProperties: {}
      }
    ];

    await act(async () => {
      await result.current.mergeTasks(importedTasks);
      await vi.advanceTimersByTimeAsync(1);
    });

    // Should have both local and imported tasks, with new ID generated for imported to avoid collisions
    expect(result.current.tasks).toHaveLength(2);
    const importedTaskFound = result.current.tasks.find(t => t.title === 'Imported Task');
    expect(importedTaskFound).toBeDefined();
    expect(importedTaskFound?.id).not.toBe('imported-1'); // ID should be regenerated by mergeTasks
  });
});
